export const RIASEC_QUESTIONS = {
  interests_activities: {
    R: [
      { id: 'R1_IA', text: 'S\'occuper de l\'entretien des plantes, du jardinage ou de l\'agriculture.' },
      { id: 'R2_IA', text: 'Réparer des appareils électriques ou électroniques défectueux.' },
      { id: 'R3_IA', text: 'Concevoir, ajuster ou réparer des vêtements et accessoires textiles.' },
      { id: 'R4_IA', text: 'Diagnostiquer et réparer des pannes mécaniques sur des véhicules.' },
      { id: 'R5_IA', text: 'Construire ou restaurer des meubles et objets en bois.' },
      { id: 'R6_IA', text: 'Manipuler des véhicules lourds pour le transport ou l\'agriculture.' },
      { id: 'R7_IA', text: 'Transporter et déplacer des meubles et objets lors de déménagements.' },
      { id: 'R8_IA', text: 'Installer ou réparer des systèmes de plomberie et de ventilation.' },
      { id: 'R9_IA', text: 'S\'occuper d\'animaux en assurant leur alimentation et leur bien-être.' },
      { id: 'R10_IA', text: 'Effectuer un travail en plein air quelles que soient les conditions météorologiques.' },
      { id: 'R11_IA', text: 'Utiliser et entretenir des machines et équipements industriels.' },
      { id: 'R12_IA', text: 'Cuisiner et organiser des repas pour des événements.' },
      { id: 'R13_IA', text: 'Utiliser divers outils manuels pour effectuer des réparations ou fabrications.' },
      { id: 'R14_IA', text: 'Appliquer de la peinture sur des surfaces pour les rénover ou les décorer.' },
      { id: 'R15_IA', text: 'Apprendre à réaliser des dessins techniques et industriels.' }
    ],
    I: [
      { id: 'I1_IA', text: 'S\'informer en lisant des articles et revues scientifiques.' },
      { id: 'I2_IA', text: 'Réaliser des études ou observations sur le comportement animal.' },
      { id: 'I3_IA', text: 'Réaliser des tests et expériences en laboratoire scientifique.' },
      { id: 'I4_IA', text: 'Apprendre et approfondir ses connaissances en sciences naturelles ou physiques.' },
      { id: 'I5_IA', text: 'Observer et analyser des symptômes pour poser un diagnostic médical.' },
      { id: 'I6_IA', text: 'Tester de nouvelles méthodes pour cultiver des plantes.' },
      { id: 'I7_IA', text: 'Concevoir des solutions innovantes pour la production d\'énergie.' },
      { id: 'I8_IA', text: 'Planifier et concevoir des infrastructures techniques et architecturales.' },
      { id: 'I9_IA', text: 'Analyser et résoudre des équations ou problèmes logiques.' },
      { id: 'I10_IA', text: 'Mener des études approfondies pour explorer de nouvelles connaissances.' },
      { id: 'I11_IA', text: 'Analyser des données économiques et rédiger un rapport d\'évaluation.' },
      { id: 'I12_IA', text: 'Élaborer un projet de reforestation et de gestion durable des espaces verts.' },
      { id: 'I13_IA', text: 'Organiser et définir des protocoles de soins médicaux.' },
      { id: 'I14_IA', text: 'Étudier et analyser les modes de vie des civilisations du passé.' },
      { id: 'I15_IA', text: 'Écrire et tester du code pour développer des logiciels et applications.' }
    ],
    A: [
      { id: 'A1_IA', text: 'Rédiger des histoires, des articles ou des chroniques journalistiques.' },
      { id: 'A2_IA', text: 'Concevoir des plans et croquis pour des objets ou espaces.' },
      { id: 'A3_IA', text: 'Jouer un rôle ou diriger une production théâtrale.' },
      { id: 'A4_IA', text: 'Participer à un groupe musical en jouant d\'un instrument.' },
      { id: 'A5_IA', text: 'Fabriquer des objets décoratifs ou utilitaires de manière artisanale.' },
      { id: 'A6_IA', text: 'Concevoir des solutions créatives et innovantes.' },
      { id: 'A7_IA', text: 'Aménager et décorer des espaces pour les rendre plus esthétiques.' },
      { id: 'A8_IA', text: 'Concevoir et réaliser des coiffures ou des vêtements.' },
      { id: 'A9_IA', text: 'Prendre et retoucher des photos pour des projets créatifs ou publicitaires.' },
      { id: 'A10_IA', text: 'Composer des bouquets et décorations florales.' },
      { id: 'A11_IA', text: 'Concevoir le scénario et l\'illustration d\'une bande dessinée.' },
      { id: 'A12_IA', text: 'Peindre des tableaux pour une exposition.' },
      { id: 'A13_IA', text: 'Concevoir et agencer des vitrines commerciales pour optimiser leur attractivité.' },
      { id: 'A14_IA', text: 'Rédiger des analyses et critiques professionnelles de pièces de théâtre, films ou ouvrages littéraires.' },
      { id: 'A15_IA', text: 'Acquérir et perfectionner des compétences en langues étrangères.' }
    ],
    S: [
      { id: 'S1_IA', text: 'Participer activement à des associations ou actions sociales.' },
      { id: 'S2_IA', text: 'Accompagner des personnes dans la gestion de leurs difficultés.' },
      { id: 'S3_IA', text: 'Encadrer et animer des activités pour jeunes enfants.' },
      { id: 'S4_IA', text: 'Transmettre et enseigner des connaissances aux enfants, adolescents ou adultes.' },
      { id: 'S5_IA', text: 'Accompagner des personnes pour les aider à mieux comprendre leur potentiel.' },
      { id: 'S6_IA', text: 'Animer et coordonner des activités pour un groupe.' },
      { id: 'S7_IA', text: 'Accueillir et orienter des participants/un public lors d\'un événement.' },
      { id: 'S8_IA', text: 'Informer le public en tenant un stand ou un kiosque.' },
      { id: 'S9_IA', text: 'Répondre aux appels pour conseiller et guider les personnes en difficulté.' },
      { id: 'S10_IA', text: 'Mener des enquêtes ou des sondages pour recueillir des avis.' },
      { id: 'S11_IA', text: 'Accompagner et soutenir des personnes en situation de handicap.' },
      { id: 'S12_IA', text: 'Assurer le suivi et le soin des personnes malades.' },
      { id: 'S13_IA', text: 'Aider à la réinsertion sociale des personnes en difficulté.' },
      { id: 'S14_IA', text: 'Organiser et encadrer des activités de loisirs.' },
      { id: 'S15_IA', text: 'Discuter et échanger des idées avec différentes personnes.' }
    ],
    E: [
      { id: 'E1_IA', text: 'Promouvoir et convaincre d\'acheter un produit ou un concept.' },
      { id: 'E2_IA', text: 'Créer et gérer une entreprise.' },
      { id: 'E3_IA', text: 'Présenter et expliquer des idées lors de conférences.' },
      { id: 'E4_IA', text: 'Gérer les achats pour une grande enseigne commerciale.' },
      { id: 'E5_IA', text: 'Négocier les prix et les conditions d\'achat ou de vente.' },
      { id: 'E6_IA', text: 'Superviser et encadrer une équipe de travail.' },
      { id: 'E7_IA', text: 'Défendre un point de vue ou une cause qui me tient à cœur.' },
      { id: 'E8_IA', text: 'Sélectionner des candidats pour un poste ou un programme.' },
      { id: 'E9_IA', text: 'S\'impliquer activement dans les événements et la vie sociale d\'une organisation.' },
      { id: 'E10_IA', text: 'Gérer les finances et le développement d\'une entreprise.' },
      { id: 'E11_IA', text: 'Développer et commercialiser un nouveau produit.' },
      { id: 'E12_IA', text: 'Créer et gérer une initiative de protection de l\'environnement ou de consommation responsable.' },
      { id: 'E13_IA', text: 'Superviser et coordonner un projet.' },
      { id: 'E14_IA', text: 'Participer activement à la politique locale ou nationale.' },
      { id: 'E15_IA', text: 'Organiser une campagne publicitaire ou un concours promotionnel.' }
    ],
    C: [
      { id: 'C1_IA', text: 'Analyser et enregistrer les dépenses dans des documents financiers.' },
      { id: 'C2_IA', text: 'Rédiger et structurer des comptes rendus.' },
      { id: 'C3_IA', text: 'Tenir une caisse dans un établissement.' },
      { id: 'C4_IA', text: 'Établir un inventaire et gérer les commandes de stock.' },
      { id: 'C5_IA', text: 'Utiliser un logiciel de traitement de texte pour la rédaction.' },
      { id: 'C6_IA', text: 'Organiser et gérer un système d\'archivage efficace.' },
      { id: 'C7_IA', text: 'Maintenir mon espace de travail propre et organisé.' },
      { id: 'C8_IA', text: 'Effectuer des calculs pour préparer des rapports financiers.' },
      { id: 'C9_IA', text: 'Réaliser des tâches répétitives et régulières avec rigueur.' },
      { id: 'C10_IA', text: 'Classer et organiser des documents administratifs.' },
      { id: 'C11_IA', text: 'Gérer les appels téléphoniques entrants et sortants.' },
      { id: 'C12_IA', text: 'Contrôler et valider des documents financiers.' },
      { id: 'C13_IA', text: 'Faire fonctionner et entretenir des équipements de bureau.' },
      { id: 'C14_IA', text: 'Réaliser des tâches avec des consignes bien définies.' },
      { id: 'C15_IA', text: 'Saisir et mettre en forme des documents écrits.' }
    ]
  },
  interests_occupations: {
    R: [
      { id: 'R1_IO', text: 'Mécanicien / mécanicienne d\'auto' },
      { id: 'R2_IO', text: 'Éleveur / éleveuse de bétails' },
      { id: 'R3_IO', text: 'Technicien / technicienne dentaire' },
      { id: 'R4_IO', text: 'Travailleur / travailleuse de la construction (menuiserie)' },
      { id: 'R5_IO', text: 'Couturier / couturière en usine' },
      { id: 'R6_IO', text: 'Technicien / technicienne en aménagement de la faune' },
      { id: 'R7_IO', text: 'Horloger / horlogère' },
      { id: 'R8_IO', text: 'Technicien / technicienne du meuble et du bois ouvré (ébéniste)' },
      { id: 'R9_IO', text: 'Plombier / plombière' },
      { id: 'R10_IO', text: 'Technicien / technicienne en mécanique du bâtiment' },
      { id: 'R11_IO', text: 'Conducteur / conductrice d\'autobus' },
      { id: 'R12_IO', text: 'Technicien / technicienne en entretien d\'aéronefs' },
      { id: 'R13_IO', text: 'Réparateur/ réparatrice de télévision' },
      { id: 'R14_IO', text: 'Ingénieur / ingénieure civil' },
      { id: 'R15_IO', text: 'Cuisinier / cuisinière' }
    ],
    I: [
      { id: 'I1_IO', text: 'Ingénieur / ingénieure en chimie, physique' },
      { id: 'I2_IO', text: 'Technicien / technicienne en laboratoire médical' },
      { id: 'I3_IO', text: 'Chercheur / chercheuse scientifique' },
      { id: 'I4_IO', text: 'Technicien / technicienne en radiologie (rayon X)' },
      { id: 'I5_IO', text: 'Biologiste' },
      { id: 'I6_IO', text: 'Technicien / technicienne en informatique' },
      { id: 'I7_IO', text: 'Médecin ou vétérinaire' },
      { id: 'I8_IO', text: 'Technicien / technicienne en transformation des produits forestiers' },
      { id: 'I9_IO', text: 'Météorologiste' },
      { id: 'I10_IO', text: 'Astronome (étudie le mouvement des astres dans le ciel)' },
      { id: 'I11_IO', text: 'Technicien / technicienne en dessin conception mécanique' },
      { id: 'I12_IO', text: 'Économiste' },
      { id: 'I13_IO', text: 'Technicien / cienne en procédés métallurgiques (spécialiste dans la transformation des métaux)' },
      { id: 'I14_IO', text: 'Botaniste' },
      { id: 'I15_IO', text: 'Technicien / cienne en chimie analytique (analyse de nouveaux produits chimiques)' }
    ],
    A: [
      { id: 'A1_IO', text: 'Musicien / musicienne' },
      { id: 'A2_IO', text: 'Écrivain / écrivaine' },
      { id: 'A3_IO', text: 'Fleuriste' },
      { id: 'A4_IO', text: 'Journaliste' },
      { id: 'A5_IO', text: 'Décorateur / décoratrice d\'intérieur' },
      { id: 'A6_IO', text: 'Compositeur / compositrice (musique)' },
      { id: 'A7_IO', text: 'Mannequin' },
      { id: 'A8_IO', text: 'Photographe' },
      { id: 'A9_IO', text: 'Graphiste' },
      { id: 'A10_IO', text: 'Directeur de publicité' },
      { id: 'A11_IO', text: 'Architecte' },
      { id: 'A12_IO', text: 'Interprète' },
      { id: 'A13_IO', text: 'Chanteur / chanteuse' },
      { id: 'A14_IO', text: 'Comédien / comédienne' },
      { id: 'A15_IO', text: 'Professeur de dessin' }
    ],
    S: [
      { id: 'S1_IO', text: 'Infirmier / infirmière auxiliaire' },
      { id: 'S2_IO', text: 'Agent / agente à l\'aide sociale' },
      { id: 'S3_IO', text: 'Travailleur / travailleuse sociale' },
      { id: 'S4_IO', text: 'Barmaid / barman' },
      { id: 'S5_IO', text: 'Professeur à l\'élémentaire' },
      { id: 'S6_IO', text: 'Technicien / technicienne en loisirs' },
      { id: 'S7_IO', text: 'Technicien / technicienne en garderie d\'enfants' },
      { id: 'S8_IO', text: 'Orthophoniste, orthopédagogue (correction des troubles de l\'apprentissage)' },
      { id: 'S9_IO', text: 'Esthéticien / esthéticienne' },
      { id: 'S10_IO', text: 'Technicien / technicienne policier / policière' },
      { id: 'S11_IO', text: 'Médecin généraliste (de famille)' },
      { id: 'S12_IO', text: 'Directeur / directrice du personnel' },
      { id: 'S13_IO', text: 'Bibliothécaire' },
      { id: 'S14_IO', text: 'Technicien / technicienne en hygiène dentaire' },
      { id: 'S15_IO', text: 'Technicien / technicienne en réadaptation physique' }
    ],
    E: [
      { id: 'E1_IO', text: 'Agent / agente de publicité (marketing)' },
      { id: 'E2_IO', text: 'Avocat / avocate' },
      { id: 'E3_IO', text: 'Agent / agente de bord' },
      { id: 'E4_IO', text: 'Chef de rayons de supermarché' },
      { id: 'E5_IO', text: 'Commis-vendeur / vendeuse' },
      { id: 'E6_IO', text: 'Directeur / directrice d\'une entreprise' },
      { id: 'E7_IO', text: 'Politicien / politicienne' },
      { id: 'E8_IO', text: 'Directeur / directrice des ventes' },
      { id: 'E9_IO', text: 'Vendeur / vendeuse d\'assurances' },
      { id: 'E10_IO', text: 'Gérant / gérante d\'hôtel' },
      { id: 'E11_IO', text: 'Technicien / technicienne en tourisme' },
      { id: 'E12_IO', text: 'Propriétaire d\'un commerce' },
      { id: 'E13_IO', text: 'Courtier / coutière en immeubles' },
      { id: 'E14_IO', text: 'Acheteur / acheteuse' },
      { id: 'E15_IO', text: 'Agent / agente de voyage' }
    ],
    C: [
      { id: 'C1_IO', text: 'Commis-comptable' },
      { id: 'C2_IO', text: 'Technicien / technicienne en finance (comptabilité)' },
      { id: 'C3_IO', text: 'Opérateur / opératrice en informatique' },
      { id: 'C4_IO', text: 'Secrétaire de service juridique, médical' },
      { id: 'C5_IO', text: 'Archiviste médical' },
      { id: 'C6_IO', text: 'Commis aux renseignements' },
      { id: 'C7_IO', text: 'Bibliotechnicien / bibliotechnicienne' },
      { id: 'C8_IO', text: 'Expert / experte en impôt' },
      { id: 'C9_IO', text: 'Caissier / caissière de banque' },
      { id: 'C10_IO', text: 'Réceptionniste' },
      { id: 'C11_IO', text: 'Commis au service de la paie' },
      { id: 'C12_IO', text: 'Gérant / gérante du service de crédits' },
      { id: 'C13_IO', text: 'Commis de bureau' },
      { id: 'C14_IO', text: 'Sténodactylo, opérateur (-trice) de saisie' },
      { id: 'C15_IO', text: 'Technicien / technicienne judiciaire (aux greffes)' }
    ]
  },
  aptitudes: {
    R: [
      { id: 'R1_AP', text: 'Ma capacité à soulever des poids lourds est :' },
      { id: 'R2_AP', text: 'Ma capacité à utiliser des outils, des objets, des machines avec précision est :' },
      { id: 'R3_AP', text: 'Mon habileté à conduire un gros véhicule (camion, autobus) est :' },
      { id: 'R4_AP', text: 'Mon aptitude à lire des plans est :' },
      { id: 'R5_AP', text: 'Mon habileté dans les mouvements demandant à voir et à manipuler en même temps est :' },
      { id: 'R6_AP', text: 'Ma capacité à comprendre le fonctionnement des éléments de base de tout ouvrage mécanique, électrique (turbine, moteur, pompe…) est :' },
      { id: 'R7_AP', text: 'La rapidité de mes réflexes est :' },
      { id: 'R8_AP', text: 'Mon habileté à faire des réparations est :' },
      { id: 'R9_AP', text: 'Ma capacité à m\'occuper d\'élevage d\'animaux est :' },
      { id: 'R10_AP', text: 'Ma capacité à installer et à manipuler divers outils, machines ou appareils est :' }
    ],
    I: [
      { id: 'I1_AP', text: 'Mes aptitudes en mathématiques sont :' },
      { id: 'I2_AP', text: 'Mes capacités en sciences (biologie, physique, chimie) sont :' },
      { id: 'I3_AP', text: 'Ma capacité à me concentrer sur une tâche abstraite est :' },
      { id: 'I4_AP', text: 'Ma capacité d\'analyse est :' },
      { id: 'I5_AP', text: 'Ma capacité de synthèse est :' },
      { id: 'I6_AP', text: 'Mon talent à rédiger clairement un texte est :' },
      { id: 'I7_AP', text: 'Ma capacité à saisir et comprendre des directives rapidement est :' },
      { id: 'I8_AP', text: 'Mon habileté à apprendre des nouveaux sujets avec facilité et avec aise est :' },
      { id: 'I9_AP', text: 'Mon habileté à solutionner des problèmes abstraits est :' },
      { id: 'I10_AP', text: 'Mon habileté à faire des travaux de laboratoire est :' }
    ],
    A: [
      { id: 'A1_AP', text: 'Ma capacité à me représenter la forme d\'objets en deux ou trois dimensions est :' },
      { id: 'A2_AP', text: 'Ma capacité à apprendre des langues, y compris ma langue maternelle est :' },
      { id: 'A3_AP', text: 'Mon aptitude en arts plastiques (dessin, sculpture, peinture, etc.) est :' },
      { id: 'A4_AP', text: 'Mon aptitude dans les arts de la scène (théâtre, danse, musique, etc.) est :' },
      { id: 'A5_AP', text: 'Ma capacité d\'inventer, de créer, de concevoir est :' },
      { id: 'A6_AP', text: 'Ma capacité à accepter la critique est :' },
      { id: 'A7_AP', text: 'Ma capacité à travailler par moi-même est :' },
      { id: 'A8_AP', text: 'Mon aptitude à exprimer concrètement mes idées créatrices dans le médium de mon choix (musique, écriture, danse, dessin, etc.) est :' },
      { id: 'A9_AP', text: 'Mon aptitude à tolérer l\'insécurité (peur du lendemain) est :' },
      { id: 'A10_AP', text: 'Mon habileté à observer les légères différences de forme ou de teinte est :' }
    ],
    S: [
      { id: 'S1_AP', text: 'Mon aptitude à travailler en équipe est :' },
      { id: 'S2_AP', text: 'Mon sens de l\'organisation est :' },
      { id: 'S3_AP', text: 'Ma faculté de prévoir, de deviner (intuition) est :' },
      { id: 'S4_AP', text: 'Ma capacité à diriger des interactions dans un groupe (animation) est :' },
      { id: 'S5_AP', text: 'Ma capacité à maintenir des relations suivies avec les gens est :' },
      { id: 'S6_AP', text: 'Mon aptitude à être touché/e par les émotions des autres, tout en demeurant objectif (empathie) est :' },
      { id: 'S7_AP', text: 'Ma capacité à réagir correctement devant les situations qui se présentent (équilibre émotionnel) est :' },
      { id: 'S8_AP', text: 'Ma capacité à aider les autres, à les comprendre, à les écouter est :' },
      { id: 'S9_AP', text: 'Ma capacité à expliquer les choses clairement est :' },
      { id: 'S10_AP', text: 'Ma capacité à communiquer avec les autres est :' }
    ],
    E: [
      { id: 'E1_AP', text: 'Ma facilité à m\'exprimer en public est :' },
      { id: 'E2_AP', text: 'Mon talent pour vendre est :' },
      { id: 'E3_AP', text: 'Mon sens des affaires est :' },
      { id: 'E4_AP', text: 'Mon habileté à diriger, à mener les autres est :' },
      { id: 'E5_AP', text: 'Ma capacité à prendre une décision seul/e est :' },
      { id: 'E6_AP', text: 'Mon habileté à me faire valoir en société est :' },
      { id: 'E7_AP', text: 'Mon aptitude à défendre une cause est :' },
      { id: 'E8_AP', text: 'Ma capacité à être le premier/ière à proposer ou à faire quelque chose est :' },
      { id: 'E9_AP', text: 'Mon talent pour persuader les gens est :' },
      { id: 'E10_AP', text: 'Ma capacité à demeurer enthousiaste et énergique même en situation difficile est :' }
    ],
    C: [
      { id: 'C1_AP', text: 'Ma capacité à me conformer aux règles établies est :' },
      { id: 'C2_AP', text: 'Mon aptitude à travailler avec précision est :' },
      { id: 'C3_AP', text: 'Ma capacité à disposer les choses selon le rang, la place qui leur convient est :' },
      { id: 'C4_AP', text: 'Mon aptitude en français est :' },
      { id: 'C5_AP', text: 'Mon aptitude à travailler avec les chiffres est :' },
      { id: 'C6_AP', text: 'Ma capacité à observer les détails est :' },
      { id: 'C7_AP', text: 'Ma capacité à m\'adapter à un travail routinier est :' },
      { id: 'C8_AP', text: 'Ma capacité à tenir des dossiers et des registres à jour est :' },
      { id: 'C9_AP', text: 'Ma capacité à comprendre et à exécuter des instructions est :' },
      { id: 'C10_AP', text: 'Mon aptitude à comprendre les structures administratives est :' }
    ]
  },
  personnalite: {
    R: [
      { id: 'R1_PE', text: 'Je respecte naturellement les règles et les procédures établies.' },
      { id: 'R2_PE', text: 'Je préfère agir discrètement plutôt que d\'attirer l\'attention.' },
      { id: 'R3_PE', text: 'Je me sens plus à l\'aise avec des tâches concrètes et pratiques qu\'avec des concepts abstraits.' },
      { id: 'R4_PE', text: 'Quand je commence une tâche, je vais jusqu\'au bout sans me décourager.' },
      { id: 'R5_PE', text: 'J\'aime passer rapidement à l\'action plutôt que de débattre trop longtemps sur les décisions.' },
      { id: 'R6_PE', text: 'Je préfère écouter et observer avant de partager mon opinion.' },
      { id: 'R7_PE', text: 'J\'accorde de l\'importance à l\'entretien et à la préservation des objets qui m\'appartiennent.' },
      { id: 'R8_PE', text: 'Je privilégie la stabilité dans mes relations et mes habitudes de vie.' },
      { id: 'R9_PE', text: 'Je suis authentique et je ne cherche pas à me conformer aux attentes des autres.' },
      { id: 'R10_PE', text: 'Je préfère dire les choses directement et honnêtement.' }
    ],
    I: [
      { id: 'I1_PE', text: 'J\'aime analyser en profondeur les situations et les événements qui m\'entourent.' },
      { id: 'I2_PE', text: 'J\'analyse les idées de manière critique et rigoureuse avant de les valider.' },
      { id: 'I3_PE', text: 'J\'ai une curiosité naturelle qui me pousse à apprendre constamment.' },
      { id: 'I4_PE', text: 'J\'aime travailler de manière autonome.' },
      { id: 'I5_PE', text: 'On me perçoit souvent comme une personne rationnelle et analytique.' },
      { id: 'I6_PE', text: 'Je trouve souvent des solutions innovantes aux problèmes que je rencontre.' },
      { id: 'I7_PE', text: 'J\'adopte une approche méthodique et rationnelle, en structurant mes tâches et en suivant une logique rigoureuse.' },
      { id: 'I8_PE', text: 'Je fais attention aux détails et à l\'exactitude dans mon travail.' },
      { id: 'I9_PE', text: 'Je préfère réfléchir avant de partager mon point de vue ou mes émotions.' },
      { id: 'I10_PE', text: 'J\'aime prendre mes décisions sur la base d\'informations précises et complètes.' }
    ],
    A: [
      { id: 'A1_PE', text: 'Ma manière de penser est parfois perçue comme non conventionnelle ou originale.' },
      { id: 'A2_PE', text: 'J\'aime explorer différentes idées sans nécessairement suivre une organisation stricte.' },
      { id: 'A3_PE', text: 'J\'aime exprimer ma créativité et ma sensibilité à travers ce que je fais.' },
      { id: 'A4_PE', text: 'J\'agis souvent selon mon intuition et mes émotions du moment.' },
      { id: 'A5_PE', text: 'Je ressens et exprime mes émotions de manière forte et spontanée.' },
      { id: 'A6_PE', text: 'J\'aime imaginer des scénarios idéaux et viser la perfection dans mes créations.' },
      { id: 'A7_PE', text: 'Je n\'hésite pas à explorer des idées originales qui sortent des sentiers battus.' },
      { id: 'A8_PE', text: 'J\'exprime mes sentiments par l\'entremise de la musique, des beaux-arts, de la poésie, etc.' },
      { id: 'A9_PE', text: 'Je me concentre sur l\'instant présent sans trop me soucier du futur.' },
      { id: 'A10_PE', text: 'J\'ai du mal à fonctionner dans un cadre rigide et préfère une grande liberté.' }
    ],
    S: [
      { id: 'S1_PE', text: 'Lorsqu\'un problème survient, je privilégie la discussion et la recherche d\'un accord.' },
      { id: 'S2_PE', text: 'Je m\'adapte facilement aux opinions et aux besoins des autres.' },
      { id: 'S3_PE', text: 'On me perçoit souvent comme quelqu\'un d\'attentionné et d\'empathique.' },
      { id: 'S4_PE', text: 'J\'aime travailler en équipe et aider les autres à atteindre leurs objectifs.' },
      { id: 'S5_PE', text: 'Je prends plaisir à interagir avec les autres et à créer des liens.' },
      { id: 'S6_PE', text: 'J\'aime aider les autres dès que j\'en ai l\'occasion.' },
      { id: 'S7_PE', text: 'Je prends en charge certaines responsabilités et les assume.' },
      { id: 'S8_PE', text: 'J\'ai l\'habitude de partager avec les autres.' },
      { id: 'S9_PE', text: 'J\'analyse souvent les situations avec justesse.' },
      { id: 'S10_PE', text: 'Je fais attention à la manière dont j\'agis et m\'exprime.' }
    ],
    E: [
      { id: 'E1_PE', text: 'J\'aime relever des défis ambitieux et me fixer des objectifs élevés.' },
      { id: 'E2_PE', text: 'J\'ai confiance en ma capacité à réussir et à surmonter les obstacles.' },
      { id: 'E3_PE', text: 'J\'exprime clairement mes idées et je les défends avec conviction.' },
      { id: 'E4_PE', text: 'J\'apprécie prendre en charge des projets et guider les autres vers un objectif.' },
      { id: 'E5_PE', text: 'Je garde mon sang-froid et je prends des décisions rapides en situation difficile.' },
      { id: 'E6_PE', text: 'J\'éprouve un attrait pour la nouveauté et l\'inconnu.' },
      { id: 'E7_PE', text: 'Je me sens généralement confiant/e dans ce que j\'entreprends.' },
      { id: 'E8_PE', text: 'J\'ai tendance à agir en fonction de mes envies du moment.' },
      { id: 'E9_PE', text: 'J\'apprécie d\'avoir un rôle actif dans l\'organisation.' },
      { id: 'E10_PE', text: 'Face à des situations tendues, je prends des décisions et agis lorsque nécessaire.' }
    ],
    C: [
      { id: 'C1_PE', text: 'Je garde mon calme, même dans des situations difficiles.' },
      { id: 'C2_PE', text: 'Je respecte facilement les règles et les consignes.' },
      { id: 'C3_PE', text: 'Je vais au bout de mes tâches avec persévérance et attention.' },
      { id: 'C4_PE', text: 'Je fais des efforts pour répondre aux attentes et bien accomplir mon travail.' },
      { id: 'C5_PE', text: 'J\'ai une approche concrète et pragmatique des situations.' },
      { id: 'C6_PE', text: 'J\'organise mon travail de manière structurée.' },
      { id: 'C7_PE', text: 'Je porte une attention particulière aux détails.' },
      { id: 'C8_PE', text: 'Je me sens à l\'aise avec des tâches répétitives d\'un jour à l\'autre.' },
      { id: 'C9_PE', text: 'Je m\'exprime peu sur mes émotions et mes pensées.' },
      { id: 'C10_PE', text: 'J\'apprécie les consignes claires qui précisent ce que l\'on attend de moi.' }
    ]
  }
};

export const RIASEC_THEMES = [
  { id: 'interests_activities', label: 'Intérêts - Activités' },
  { id: 'interests_occupations', label: 'Intérêts - Occupations' },
  { id: 'aptitudes', label: 'Aptitudes' },
  { id: 'personnalite', label: 'Personnalité' }
];

export const RIASEC_LETTERS = [
  { id: 'R', label: 'Réaliste' },
  { id: 'I', label: 'Investigateur' },
  { id: 'A', label: 'Artistique' },
  { id: 'S', label: 'Social' },
  { id: 'E', label: 'Entreprenant' },
  { id: 'C', label: 'Conventionnel' }
];

export const TIPI_QUESTIONS = [
  { id: 'TIPI1', text: 'Extraverti, enthousiaste' },
  { id: 'TIPI2', text: 'Critique, querelleur' },
  { id: 'TIPI3', text: 'Fiable, autodiscipliné' },
  { id: 'TIPI4', text: 'Anxieux, facilement perturbé' },
  { id: 'TIPI5', text: 'Ouvert aux nouvelles expériences, complexe' },
  { id: 'TIPI6', text: 'Réservé, calme' },
  { id: 'TIPI7', text: 'Sympathique, chaleureux' },
  { id: 'TIPI8', text: 'Désorganisé, négligent' },
  { id: 'TIPI9', text: 'Calme, émotionnellement stable' },
  { id: 'TIPI10', text: 'Conventionnel, peu créatif' }
];

export const VOCABULARY_WORDS = [
  { id: 'VCL1', text: 'boat' },
  { id: 'VCL2', text: 'incoherent' },
  { id: 'VCL3', text: 'pallid' },
  { id: 'VCL4', text: 'robot' },
  { id: 'VCL5', text: 'audible' },
  { id: 'VCL6', text: 'cuivocal' },
  { id: 'VCL7', text: 'paucity' },
  { id: 'VCL8', text: 'epistemology' },
  { id: 'VCL9', text: 'florted' },
  { id: 'VCL10', text: 'decide' },
  { id: 'VCL11', text: 'pastiche' },
  { id: 'VCL12', text: 'verdid' },
  { id: 'VCL13', text: 'abysmal' },
  { id: 'VCL14', text: 'lucid' },
  { id: 'VCL15', text: 'betray' },
  { id: 'VCL16', text: 'funny' }
];

export const RIASEC_SCALE = [
  { value: 0, label: 'Non' },
  { value: 1, label: 'Oui' }
];

export const TIPI_SCALE = [
  { value: 1, label: 'Pas du tout d\'accord' },
  { value: 2, label: 'Pas d\'accord' },
  { value: 3, label: 'Plutôt pas d\'accord' },
  { value: 4, label: 'Ni d\'accord ni en désaccord' },
  { value: 5, label: 'Plutôt d\'accord' },
  { value: 6, label: 'D\'accord' },
  { value: 7, label: 'Tout à fait d\'accord' }
]; 