export const RIASEC_QUESTIONS = {
  interests_activities: {
    R: [
      { id: 'R1_IA', text: 'Planter, entretenir des arbres, des arbustes, des fleurs ou cultiver le sol' },
      { id: 'R2_IA', text: 'Effectuer des réparations électriques ou électroniques' },
      { id: 'R3_IA', text: 'Faire de la couture' },
      { id: 'R4_IA', text: 'Réparer des automobiles' },
      { id: 'R5_IA', text: 'Fabriquer des objets avec du bois' },
      { id: 'R6_IA', text: 'Conduire un camion ou un tracteur' },
      { id: 'R7_IA', text: 'Faire des déménagements' },
      { id: 'R8_IA', text: 'Entretenir ou réparer de la plomberie ou des systèmes de ventilation' },
      { id: 'R9_IA', text: 'Travailler avec des animaux et en prendre soin' },
      { id: 'R10_IA', text: 'Travailler à l\'extérieur (exposer à la pluie, au soleil, au froid)' },
      { id: 'R11_IA', text: 'Travailler avec de la machinerie' },
      { id: 'R12_IA', text: 'Préparer des repas, des banquets' },
      { id: 'R13_IA', text: 'Travailler avec des outils tels que tournevis, ciseaux, pince, etc.' },
      { id: 'R14_IA', text: 'Effectuer des travaux de peinture' },
      { id: 'R15_IA', text: 'Suivre un cours de dessin mécanique' }
    ],
    I: [
      { id: 'I1_IA', text: 'Lire des revues scientifiques ou spécialisées' },
      { id: 'I2_IA', text: 'Faire des expériences sur le comportement des animaux' },
      { id: 'I3_IA', text: 'Effectuer des analyses en laboratoire' },
      { id: 'I4_IA', text: 'Suivre des cours de sciences' },
      { id: 'I5_IA', text: 'Établir un diagnostic de maladie chez des patients' },
      { id: 'I6_IA', text: 'Expérimenter de nouvelles cultures végétales' },
      { id: 'I7_IA', text: 'Créer une nouvelle source d\'énergie' },
      { id: 'I8_IA', text: 'Concevoir un barrage électrique, un pont, une autoroute, etc.' },
      { id: 'I9_IA', text: 'Résoudre des problèmes mathématiques' },
      { id: 'I10_IA', text: 'Faire des recherches scientifiques pour satisfaire ma curiosité' },
      { id: 'I11_IA', text: 'Produire un rapport sur l\'évolution économique d\'une région' },
      { id: 'I12_IA', text: 'Concevoir un plan de reboisement' },
      { id: 'I13_IA', text: 'Planifier des soins ou des traitements à donner à des patients' },
      { id: 'I14_IA', text: 'Faire des recherches sur les civilisations anciennes' },
      { id: 'I15_IA', text: 'Faire de la programmation informatique' }
    ],
    A: [
      { id: 'A1_IA', text: 'Écrire des romans, des articles de journaux' },
      { id: 'A2_IA', text: 'Dessiner des meubles, des plans de maison, des décors, etc.' },
      { id: 'A3_IA', text: 'Interpréter ou mettre en scène une pièce de théâtre' },
      { id: 'A4_IA', text: 'Jouer dans un orchestre' },
      { id: 'A5_IA', text: 'Créer des pièces d\'artisanat' },
      { id: 'A6_IA', text: 'Imaginer de nouvelles façons de faire les choses' },
      { id: 'A7_IA', text: 'Embellir l\'environnement' },
      { id: 'A8_IA', text: 'Créer une nouvelle coupe de cheveux ou de nouveau vêtement' },
      { id: 'A9_IA', text: 'Faire de la photographie publicitaire ou artistique' },
      { id: 'A10_IA', text: 'Concevoir et réaliser des arrangements de fleurs' },
      { id: 'A11_IA', text: 'Imaginer une bande dessinée' },
      { id: 'A12_IA', text: 'Peindre des tableaux pour une exposition' },
      { id: 'A13_IA', text: 'Décorer des vitrines de magasins' },
      { id: 'A14_IA', text: 'Écrire des critiques de pièces de théâtre, de films, de livres, etc.' },
      { id: 'A15_IA', text: 'Apprendre des langues' }
    ],
    S: [
      { id: 'S1_IA', text: 'S\'engager dans des organismes sociaux ou communautaires' },
      { id: 'S2_IA', text: 'Rencontrer des gens pour les aider à résoudre leurs problèmes personnels' },
      { id: 'S3_IA', text: 'Travailler dans une garderie d\'enfants' },
      { id: 'S4_IA', text: 'Enseigner aux enfants, aux adolescents, aux adultes' },
      { id: 'S5_IA', text: 'Aider les gens à prendre conscience de leurs possibilités' },
      { id: 'S6_IA', text: 'Animer un groupe' },
      { id: 'S7_IA', text: 'Agir comme hôte / hôtesse lors d\'un congrès' },
      { id: 'S8_IA', text: 'Tenir un kiosque d\'information' },
      { id: 'S9_IA', text: 'Offrir un service d\'aide téléphonique' },
      { id: 'S10_IA', text: 'Consulter les gens sur leurs besoins (sondage, enquête, etc.)' },
      { id: 'S11_IA', text: 'S\'occuper des personnes handicapées physiquement' },
      { id: 'S12_IA', text: 'Soigner un malade' },
      { id: 'S13_IA', text: 'Aider les délinquants à se réhabiliter' },
      { id: 'S14_IA', text: 'Organiser des loisirs' },
      { id: 'S15_IA', text: 'Échanger des idées avec d\'autres personnes' }
    ],
    E: [
      { id: 'E1_IA', text: 'Vendre un produit ou une idée' },
      { id: 'E2_IA', text: 'Mettre sur pied son propre commerce' },
      { id: 'E3_IA', text: 'Donner des conférences' },
      { id: 'E4_IA', text: 'Acheter pour le compte d\'un grand magasin' },
      { id: 'E5_IA', text: 'Marchander' },
      { id: 'E6_IA', text: 'Diriger du personnel' },
      { id: 'E7_IA', text: 'Défendre une cause' },
      { id: 'E8_IA', text: 'Faire de la sélection de candidats' },
      { id: 'E9_IA', text: 'S\'engager à fond dans des activités sociales au travail ou dans son quartier' },
      { id: 'E10_IA', text: 'Diriger une entreprise financière' },
      { id: 'E11_IA', text: 'Lancer un nouveau produit' },
      { id: 'E12_IA', text: 'Fonder un club de consommateurs, une association de protection de l\'environnement, une activité de récupération de papier' },
      { id: 'E13_IA', text: 'Gérer un projet spécial' },
      { id: 'E14_IA', text: 'Faire de la politique (municipal, scolaire, provincial)' },
      { id: 'E15_IA', text: 'Lancer un concours de promotion, une campagne de publicité' }
    ],
    C: [
      { id: 'C1_IA', text: 'Établir des comptes-rendus des dépenses' },
      { id: 'C2_IA', text: 'Préparer des procès-verbaux de réunions' },
      { id: 'C3_IA', text: 'Tenir une caisse dans un établissement commercial ou financier' },
      { id: 'C4_IA', text: 'Faire un inventaire et passer des commandes' },
      { id: 'C5_IA', text: 'Manipuler un appareil à traitement de textes' },
      { id: 'C6_IA', text: 'Maintenir un système de classement (archive, bibliothèque, bureau, etc.)' },
      { id: 'C7_IA', text: 'Garder mon espace de travail à l\'ordre' },
      { id: 'C8_IA', text: 'Faire des opérations mathématiques pour préparer des rapports ou faire la tenue de livres' },
      { id: 'C9_IA', text: 'S\'adonner à des activités régulières' },
      { id: 'C10_IA', text: 'Classer des lettres, des rapports, des dossiers' },
      { id: 'C11_IA', text: 'Recevoir et faire des appels téléphoniques' },
      { id: 'C12_IA', text: 'Vérifier des rapports financiers' },
      { id: 'C13_IA', text: 'Faire fonctionner toutes sortes de machines de bureau' },
      { id: 'C14_IA', text: 'Effectuer des tâches clairement définies' },
      { id: 'C15_IA', text: 'Dactylographier ou réviser des lettres ou des rapports' }
    ]
  },
  interests_occupations: {
    R: [
      { id: 'R1_IO', text: 'Mécanicien / mécanicienne d\'auto' },
      { id: 'R2_IO', text: 'Éleveur / éleveuse de bétails' },
      { id: 'R3_IO', text: 'Technicien / technicienne dentaire' },
      { id: 'R4_IO', text: 'Travailleur / travailleuse de la construction (menuiserie)' },
      { id: 'R5_IO', text: 'Couturier / couturière en usine' },
      { id: 'R6_IO', text: 'Technicien / technicienne en aménagement de la faune' },
      { id: 'R7_IO', text: 'Horloger / horlogère' },
      { id: 'R8_IO', text: 'Technicien / technicienne du meuble et du bois ouvré (ébéniste)' },
      { id: 'R9_IO', text: 'Plombier / plombière' },
      { id: 'R10_IO', text: 'Technicien / technicienne en mécanique du bâtiment' },
      { id: 'R11_IO', text: 'Conducteur / conductrice d\'autobus' },
      { id: 'R12_IO', text: 'Technicien / technicienne en entretien d\'aéronefs' },
      { id: 'R13_IO', text: 'Réparateur/ réparatrice de télévision' },
      { id: 'R14_IO', text: 'Ingénieur / ingénieure civil' },
      { id: 'R15_IO', text: 'Cuisinier / cuisinière' }
    ],
    I: [
      { id: 'I1_IO', text: 'Ingénieur / ingénieure en chimie, physique' },
      { id: 'I2_IO', text: 'Technicien / technicienne en laboratoire médical' },
      { id: 'I3_IO', text: 'Chercheur / chercheuse scientifique' },
      { id: 'I4_IO', text: 'Technicien / technicienne en radiologie (rayon X)' },
      { id: 'I5_IO', text: 'Biologiste' },
      { id: 'I6_IO', text: 'Technicien / technicienne en informatique' },
      { id: 'I7_IO', text: 'Médecin ou vétérinaire' },
      { id: 'I8_IO', text: 'Technicien / technicienne en transformation des produits forestiers' },
      { id: 'I9_IO', text: 'Météorologiste' },
      { id: 'I10_IO', text: 'Astronome (étudie le mouvement des astres dans le ciel)' },
      { id: 'I11_IO', text: 'Technicien / technicienne en dessin conception mécanique' },
      { id: 'I12_IO', text: 'Économiste' },
      { id: 'I13_IO', text: 'Technicien / cienne en procédés métallurgiques (spécialiste dans la transformation des métaux)' },
      { id: 'I14_IO', text: 'Botaniste' },
      { id: 'I15_IO', text: 'Technicien / cienne en chimie analytique (analyse de nouveaux produits chimiques)' }
    ],
    A: [
      { id: 'A1_IO', text: 'Musicien / musicienne' },
      { id: 'A2_IO', text: 'Écrivain / écrivaine' },
      { id: 'A3_IO', text: 'Fleuriste' },
      { id: 'A4_IO', text: 'Journaliste' },
      { id: 'A5_IO', text: 'Décorateur / décoratrice d\'intérieur' },
      { id: 'A6_IO', text: 'Compositeur / compositrice (musique)' },
      { id: 'A7_IO', text: 'Mannequin' },
      { id: 'A8_IO', text: 'Photographe' },
      { id: 'A9_IO', text: 'Graphiste' },
      { id: 'A10_IO', text: 'Directeur de publicité' },
      { id: 'A11_IO', text: 'Architecte' },
      { id: 'A12_IO', text: 'Interprète' },
      { id: 'A13_IO', text: 'Chanteur / chanteuse' },
      { id: 'A14_IO', text: 'Comédien / comédienne' },
      { id: 'A15_IO', text: 'Professeur de dessin' }
    ],
    S: [
      { id: 'S1_IO', text: 'Infirmier / infirmière auxiliaire' },
      { id: 'S2_IO', text: 'Agent / agente à l\'aide sociale' },
      { id: 'S3_IO', text: 'Travailleur / travailleuse sociale' },
      { id: 'S4_IO', text: 'Barmaid / barman' },
      { id: 'S5_IO', text: 'Professeur à l\'élémentaire' },
      { id: 'S6_IO', text: 'Technicien / technicienne en loisirs' },
      { id: 'S7_IO', text: 'Technicien / technicienne en garderie d\'enfants' },
      { id: 'S8_IO', text: 'Orthophoniste, orthopédagogue (correction des troubles de l\'apprentissage)' },
      { id: 'S9_IO', text: 'Esthéticien / esthéticienne' },
      { id: 'S10_IO', text: 'Technicien / technicienne policier / policière' },
      { id: 'S11_IO', text: 'Médecin généraliste (de famille)' },
      { id: 'S12_IO', text: 'Directeur / directrice du personnel' },
      { id: 'S13_IO', text: 'Bibliothécaire' },
      { id: 'S14_IO', text: 'Technicien / technicienne en hygiène dentaire' },
      { id: 'S15_IO', text: 'Technicien / technicienne en réadaptation physique' }
    ],
    E: [
      { id: 'E1_IO', text: 'Agent / agente de publicité (marketing)' },
      { id: 'E2_IO', text: 'Avocat / avocate' },
      { id: 'E3_IO', text: 'Agent / agente de bord' },
      { id: 'E4_IO', text: 'Chef de rayons de supermarché' },
      { id: 'E5_IO', text: 'Commis-vendeur / vendeuse' },
      { id: 'E6_IO', text: 'Directeur / directrice d\'une entreprise' },
      { id: 'E7_IO', text: 'Politicien / politicienne' },
      { id: 'E8_IO', text: 'Directeur / directrice des ventes' },
      { id: 'E9_IO', text: 'Vendeur / vendeuse d\'assurances' },
      { id: 'E10_IO', text: 'Gérant / gérante d\'hôtel' },
      { id: 'E11_IO', text: 'Technicien / technicienne en tourisme' },
      { id: 'E12_IO', text: 'Propriétaire d\'un commerce' },
      { id: 'E13_IO', text: 'Courtier / coutière en immeubles' },
      { id: 'E14_IO', text: 'Acheteur / acheteuse' },
      { id: 'E15_IO', text: 'Agent / agente de voyage' }
    ],
    C: [
      { id: 'C1_IO', text: 'Commis-comptable' },
      { id: 'C2_IO', text: 'Technicien / technicienne en finance (comptabilité)' },
      { id: 'C3_IO', text: 'Opérateur / opératrice en informatique' },
      { id: 'C4_IO', text: 'Secrétaire de service juridique, médical' },
      { id: 'C5_IO', text: 'Archiviste médical' },
      { id: 'C6_IO', text: 'Commis aux renseignements' },
      { id: 'C7_IO', text: 'Bibliotechnicien / bibliotechnicienne' },
      { id: 'C8_IO', text: 'Expert / experte en impôt' },
      { id: 'C9_IO', text: 'Caissier / caissière de banque' },
      { id: 'C10_IO', text: 'Réceptionniste' },
      { id: 'C11_IO', text: 'Commis au service de la paie' },
      { id: 'C12_IO', text: 'Gérant / gérante du service de crédits' },
      { id: 'C13_IO', text: 'Commis de bureau' },
      { id: 'C14_IO', text: 'Sténodactylo, opérateur (-trice) de saisie' },
      { id: 'C15_IO', text: 'Technicien / technicienne judiciaire (aux greffes)' }
    ]
  },
  aptitudes: {
    R: [
      { id: 'R1_AP', text: 'Ma capacité à soulever des poids lourds est :' },
      { id: 'R2_AP', text: 'Ma capacité à utiliser des outils, des objets, des machines avec précision est :' },
      { id: 'R3_AP', text: 'Mon habileté à conduire un gros véhicule (camion, autobus) est :' },
      { id: 'R4_AP', text: 'Mon aptitude à lire des plans est :' },
      { id: 'R5_AP', text: 'Mon habileté dans les mouvements demandant à voir et à manipuler en même temps est :' },
      { id: 'R6_AP', text: 'Ma capacité à comprendre le fonctionnement des éléments de base de tout ouvrage mécanique, électrique (turbine, moteur, pompe…) est :' },
      { id: 'R7_AP', text: 'La rapidité de mes réflexes est :' },
      { id: 'R8_AP', text: 'Mon habileté à faire des réparations est :' },
      { id: 'R9_AP', text: 'Ma capacité à m\'occuper d\'élevage d\'animaux est :' },
      { id: 'R10_AP', text: 'Ma capacité à installer et à manipuler divers outils, machines ou appareils est :' }
    ],
    I: [
      { id: 'I1_AP', text: 'Mes aptitudes en mathématiques sont :' },
      { id: 'I2_AP', text: 'Mes capacités en sciences (biologie, physique, chimie) sont :' },
      { id: 'I3_AP', text: 'Ma capacité à me concentrer sur une tâche abstraite est :' },
      { id: 'I4_AP', text: 'Ma capacité d\'analyse est :' },
      { id: 'I5_AP', text: 'Ma capacité de synthèse est :' },
      { id: 'I6_AP', text: 'Mon talent à rédiger clairement un texte est :' },
      { id: 'I7_AP', text: 'Ma capacité à saisir et comprendre des directives rapidement est :' },
      { id: 'I8_AP', text: 'Mon habileté à apprendre des nouveaux sujets avec facilité et avec aise est :' },
      { id: 'I9_AP', text: 'Mon habileté à solutionner des problèmes abstraits est :' },
      { id: 'I10_AP', text: 'Mon habileté à faire des travaux de laboratoire est :' }
    ],
    A: [
      { id: 'A1_AP', text: 'Ma capacité à me représenter la forme d\'objets en deux ou trois dimensions est :' },
      { id: 'A2_AP', text: 'Ma capacité à apprendre des langues, y compris ma langue maternelle est :' },
      { id: 'A3_AP', text: 'Mon aptitude en arts plastiques (dessin, sculpture, peinture, etc.) est :' },
      { id: 'A4_AP', text: 'Mon aptitude dans les arts de la scène (théâtre, danse, musique, etc.) est :' },
      { id: 'A5_AP', text: 'Ma capacité d\'inventer, de créer, de concevoir est :' },
      { id: 'A6_AP', text: 'Ma capacité à accepter la critique est :' },
      { id: 'A7_AP', text: 'Ma capacité à travailler par moi-même est :' },
      { id: 'A8_AP', text: 'Mon aptitude à exprimer concrètement mes idées créatrices dans le médium de mon choix (musique, écriture, danse, dessin, etc.) est :' },
      { id: 'A9_AP', text: 'Mon aptitude à tolérer l\'insécurité (peur du lendemain) est :' },
      { id: 'A10_AP', text: 'Mon habileté à observer les légères différences de forme ou de teinte est :' }
    ],
    S: [
      { id: 'S1_AP', text: 'Mon aptitude à travailler en équipe est :' },
      { id: 'S2_AP', text: 'Mon sens de l\'organisation est :' },
      { id: 'S3_AP', text: 'Ma faculté de prévoir, de deviner (intuition) est :' },
      { id: 'S4_AP', text: 'Ma capacité à diriger des interactions dans un groupe (animation) est :' },
      { id: 'S5_AP', text: 'Ma capacité à maintenir des relations suivies avec les gens est :' },
      { id: 'S6_AP', text: 'Mon aptitude à être touché/e par les émotions des autres, tout en demeurant objectif (empathie) est :' },
      { id: 'S7_AP', text: 'Ma capacité à réagir correctement devant les situations qui se présentent (équilibre émotionnel) est :' },
      { id: 'S8_AP', text: 'Ma capacité à aider les autres, à les comprendre, à les écouter est :' },
      { id: 'S9_AP', text: 'Ma capacité à expliquer les choses clairement est :' },
      { id: 'S10_AP', text: 'Ma capacité à communiquer avec les autres est :' }
    ],
    E: [
      { id: 'E1_AP', text: 'Ma facilité à m\'exprimer en public est :' },
      { id: 'E2_AP', text: 'Mon talent pour vendre est :' },
      { id: 'E3_AP', text: 'Mon sens des affaires est :' },
      { id: 'E4_AP', text: 'Mon habileté à diriger, à mener les autres est :' },
      { id: 'E5_AP', text: 'Ma capacité à prendre une décision seul/e est :' },
      { id: 'E6_AP', text: 'Mon habileté à me faire valoir en société est :' },
      { id: 'E7_AP', text: 'Mon aptitude à défendre une cause est :' },
      { id: 'E8_AP', text: 'Ma capacité à être le premier/ière à proposer ou à faire quelque chose est :' },
      { id: 'E9_AP', text: 'Mon talent pour persuader les gens est :' },
      { id: 'E10_AP', text: 'Ma capacité à demeurer enthousiaste et énergique même en situation difficile est :' }
    ],
    C: [
      { id: 'C1_AP', text: 'Ma capacité à me conformer aux règles établies est :' },
      { id: 'C2_AP', text: 'Mon aptitude à travailler avec précision est :' },
      { id: 'C3_AP', text: 'Ma capacité à disposer les choses selon le rang, la place qui leur convient est :' },
      { id: 'C4_AP', text: 'Mon aptitude en français est :' },
      { id: 'C5_AP', text: 'Mon aptitude à travailler avec les chiffres est :' },
      { id: 'C6_AP', text: 'Ma capacité à observer les détails est :' },
      { id: 'C7_AP', text: 'Ma capacité à m\'adapter à un travail routinier est :' },
      { id: 'C8_AP', text: 'Ma capacité à tenir des dossiers et des registres à jour est :' },
      { id: 'C9_AP', text: 'Ma capacité à comprendre et à exécuter des instructions est :' },
      { id: 'C10_AP', text: 'Mon aptitude à comprendre les structures administratives est :' }
    ]
  },
  personnalite: {
    R: [
      { id: 'R1_PE', text: 'Je suis conformiste, je me plie facilement aux règlements du milieu où je vis.' },
      { id: 'R2_PE', text: 'Généralement, j\'évite de me faire remarquer.' },
      { id: 'R3_PE', text: 'J\'aime les choses matérielles, concrètes.' },
      { id: 'R4_PE', text: 'Dans mon travail ou autres, je me montre persistant/e' },
      { id: 'R5_PE', text: 'Je démontre un esprit d\'équipe pratique et je préfère agir plutôt que de discuter trop longuement de ce que l\'on va faire.' },
      { id: 'R6_PE', text: 'Je suis d\'un naturel réservé ; pour savoir mon opinion, on doit me le demander.' },
      { id: 'R7_PE', text: 'Je suis porté/e à ménager et à prendre soin de mes biens.' },
      { id: 'R8_PE', text: 'Je suis stable dans mes opinions, ma façon de vivre, mes amitiés.' },
      { id: 'R9_PE', text: 'Je me présente toujours au naturel, tel que je suis.' },
      { id: 'R10_PE', text: 'Avec mon entourage, je suis franc/che et sincère.' }
    ],
    I: [
      { id: 'I1_PE', text: 'J\'analyse les idées, les événements, ce qui se passe autour de moi.' },
      { id: 'I2_PE', text: 'J\'ai l\'esprit critique et n\'accepte pas facilement n\'importe quelle idée.' },
      { id: 'I3_PE', text: 'Je suis d\'un naturel très curieux sur à peu près tout.' },
      { id: 'I4_PE', text: 'Je tiens à mon indépendance sur le plan des idées, du travail, etc.' },
      { id: 'I5_PE', text: 'Les gens me considèrent comme une personne intellectuelle plutôt qu\'émotive.' },
      { id: 'I6_PE', text: 'J\'ai l\'esprit inventif : il m\'arrive souvent de trouver une solution originale et efficace à un problème.' },
      { id: 'I7_PE', text: 'Dans mes activités scolaires ou autres, je me montre méthodique et rationnel/le.' },
      { id: 'I8_PE', text: 'J\'aime la précision dans tout ce que je fais.' },
      { id: 'I9_PE', text: 'Je demeure réservé/e dans l\'expression de mes opinions, de mes sentiments et de mes actes.' },
      { id: 'I10_PE', text: 'Avant toute décision, je réunis le maximum d\'information possible.' }
    ],
    A: [
      { id: 'A1_PE', text: 'Mes amis/es me considèrent compliqué/e' },
      { id: 'A2_PE', text: 'Dans mes diverses activités, je manque souvent d\'ordre' },
      { id: 'A3_PE', text: 'Dans mes travaux, je fais preuve d\'originalité, d\'imagination et d\'intuition.' },
      { id: 'A4_PE', text: 'Je suis d\'un caractère impulsif.' },
      { id: 'A5_PE', text: 'Mes émotions sont généralement intenses.' },
      { id: 'A6_PE', text: 'Je suis porté/e à tout idéaliser et à chercher la perfection.' },
      { id: 'A7_PE', text: 'J\'agis et je pense souvent de façon non conformisme, c\'est-à-dire différemment des autres.' },
      { id: 'A8_PE', text: 'J\'exprime mes sentiments par l\'entremise de la musique, des beaux-arts, de la poésie, etc.' },
      { id: 'A9_PE', text: 'Les lendemains ne m\'inquiètent pas : je vis au jour le jour.' },
      { id: 'A10_PE', text: 'J\'ai besoin de beaucoup de liberté d\'action dans tout ce que j\'entreprends.' }
    ],
    S: [
      { id: 'S1_PE', text: 'Quand un problème se pose, je préfère le régler par la discussion et l\'entente avec les gens qui m\'entourent.' },
      { id: 'S2_PE', text: 'Je sais me montrer souple, conciliant/e' },
      { id: 'S3_PE', text: 'Mes amis/es me considèrent comme bienveillant et compréhensif/ve.' },
      { id: 'S4_PE', text: 'Généralement, les gens peuvent compter sur ma coopération.' },
      { id: 'S5_PE', text: 'Les gens me qualifient de sociable et sympathique.' },
      { id: 'S6_PE', text: 'Je suis d\'un naturel serviable.' },
      { id: 'S7_PE', text: 'J\'accepte et j\'assume des responsabilités.' },
      { id: 'S8_PE', text: 'On me considère généreux/se.' },
      { id: 'S9_PE', text: 'Dans la majorité des circonstances, je suis perspicace, clairvoyant/e.' },
      { id: 'S10_PE', text: 'Dans l\'action comme dans la façon de m\'exprimer, je montre de la délicatesse.' }
    ],
    E: [
      { id: 'E1_PE', text: 'L\'ambition ne m\'effraie pas.' },
      { id: 'E2_PE', text: 'Je suis un/e optimiste né/e.' },
      { id: 'E3_PE', text: 'Je suis sociable et populaire ; je parle à tout le monde.' },
      { id: 'E4_PE', text: 'Je défends toujours mes opinions.' },
      { id: 'E5_PE', text: 'Il m\'arrive souvent de me montrer autoritaire.' },
      { id: 'E6_PE', text: 'L\'aventure m\'attire beaucoup.' },
      { id: 'E7_PE', text: 'Généralement, je suis sûr/e de moi.' },
      { id: 'E8_PE', text: 'Mes impulsions me dictent souvent ma conduite.' },
      { id: 'E9_PE', text: 'J\'aime être responsable d\'activités.' },
      { id: 'E10_PE', text: 'Même dans des situations critiques ou tendues, je sais prendre l\'initiative nécessaire.' }
    ],
    C: [
      { id: 'C1_PE', text: 'Je suis maître de moi, d\'un calme exemplaire.' },
      { id: 'C2_PE', text: 'J\'obéis facilement aux règlements et aux ordres.' },
      { id: 'C3_PE', text: 'Dans mes travaux, je suis persistant/e et consciencieux/se.' },
      { id: 'C4_PE', text: 'Je m\'efforce de me montrer compétent dans ce qu\'on exige de moi.' },
      { id: 'C5_PE', text: 'L\'esprit concret et pratique me guide.' },
      { id: 'C6_PE', text: 'J\'agis méthodiquement dans tout ce que je fais.' },
      { id: 'C7_PE', text: 'Je travaille avec beaucoup de soin.' },
      { id: 'C8_PE', text: 'D\'une journée à l\'autre, j\'aime exécuter des tâches semblables.' },
      { id: 'C9_PE', text: 'Je suis timide et je préfère garder pour moi mes sentiments, mes émotions et mes idées.' },
      { id: 'C10_PE', text: 'J\'aime recevoir des instructions bien claires qui me permettent de savoir exactement ce qu\'on attend de moi.' }
    ]
  }
};

export const RIASEC_THEMES = [
  { id: 'interests_activities', label: 'Intérêts - Activités' },
  { id: 'interests_occupations', label: 'Intérêts - Occupations' },
  { id: 'aptitudes', label: 'Aptitudes' },
  { id: 'personnalite', label: 'Personnalité' }
];

export const RIASEC_LETTERS = [
  { id: 'R', label: 'Réaliste' },
  { id: 'I', label: 'Investigateur' },
  { id: 'A', label: 'Artistique' },
  { id: 'S', label: 'Social' },
  { id: 'E', label: 'Entreprenant' },
  { id: 'C', label: 'Conventionnel' }
];

export const TIPI_QUESTIONS = [
  { id: 'TIPI1', text: 'Extraverti, enthousiaste' },
  { id: 'TIPI2', text: 'Critique, querelleur' },
  { id: 'TIPI3', text: 'Fiable, autodiscipliné' },
  { id: 'TIPI4', text: 'Anxieux, facilement perturbé' },
  { id: 'TIPI5', text: 'Ouvert aux nouvelles expériences, complexe' },
  { id: 'TIPI6', text: 'Réservé, calme' },
  { id: 'TIPI7', text: 'Sympathique, chaleureux' },
  { id: 'TIPI8', text: 'Désorganisé, négligent' },
  { id: 'TIPI9', text: 'Calme, émotionnellement stable' },
  { id: 'TIPI10', text: 'Conventionnel, peu créatif' }
];

export const VOCABULARY_WORDS = [
  { id: 'VCL1', text: 'boat' },
  { id: 'VCL2', text: 'incoherent' },
  { id: 'VCL3', text: 'pallid' },
  { id: 'VCL4', text: 'robot' },
  { id: 'VCL5', text: 'audible' },
  { id: 'VCL6', text: 'cuivocal' },
  { id: 'VCL7', text: 'paucity' },
  { id: 'VCL8', text: 'epistemology' },
  { id: 'VCL9', text: 'florted' },
  { id: 'VCL10', text: 'decide' },
  { id: 'VCL11', text: 'pastiche' },
  { id: 'VCL12', text: 'verdid' },
  { id: 'VCL13', text: 'abysmal' },
  { id: 'VCL14', text: 'lucid' },
  { id: 'VCL15', text: 'betray' },
  { id: 'VCL16', text: 'funny' }
];

export const RIASEC_SCALE = [
  { value: 0, label: 'Non' },
  { value: 1, label: 'Oui' }
];

export const TIPI_SCALE = [
  { value: 1, label: 'Pas du tout d\'accord' },
  { value: 2, label: 'Pas d\'accord' },
  { value: 3, label: 'Plutôt pas d\'accord' },
  { value: 4, label: 'Ni d\'accord ni en désaccord' },
  { value: 5, label: 'Plutôt d\'accord' },
  { value: 6, label: 'D\'accord' },
  { value: 7, label: 'Tout à fait d\'accord' }
]; 